### ISSUE TITLE
no output when using format PNM

### ISSUE THREAD

**Issue by splace** [spakin/netpbm#4]
i get nothing read and no error, (although i see in the code it is trying to send to stderr a message, it doesn't seem to be output, for me anyway.) 

seems to me that when PNM option then it should use the images netbpm format (if one of these), then use PAM as nil option does.

**Comment by splace** [comment]
also there would a possibility of some nice flexible selection;

by using the std.lib type (and pallette size/values) to select the PNM format.

Eg. if palletted with only black/white then use PBM format for the PNM.

**Comment by splace** [comment]
i'm still not getting an encoding for a std.lib image, when PNM option set.

**Comment by spakin** [comment]
Could you please attach a short `.go` file that I can use for testing?

**Comment by splace** [comment]
below code returns just the header, (which in my non-cut-down code it didn't) and here, if i switch to text mode, the raster is there!

also, in this cut-down code other formats are also missing the raster.

is it possibly there is an internal buffer/thread that sometimes hasn't finished when the program ends? (guess)  i would say 'encoders' need to flush before returning.

```
package main

import "image"
import "os"

import "github.com/spakin/netpbm"

func main() {
	netpbm.Encode(os.Stdout, image.NewRGBA(image.Rect(0,0,10,10)), &netpbm.EncodeOptions{netpbm.PNM,0,false,nil})
}

/* run: arguments="" hal3 Thu 11 Jul 16:37:54 BST 2019 go version go1.12.6 linux/amd64
P7
WIDTH 10
HEIGHT 10
DEPTH 4
MAXVAL 255
TUPLTYPE RGB_ALPHA
ENDHDR
Thu 11 Jul 16:37:54 BST 2019
*/
```

**Comment by spakin** [comment]
When I run the above (modified slightly to honor the latest definition of `netpbm.EncodeOptions`), I do see the encoded data.  Note that it's all zeroes, though, so it may not show up on your screen.  Here's what I get by piping the output into `od -c`:

```
0000000   P   7  \n   W   I   D   T   H       1   0  \n   H   E   I   G
0000020   H   T       1   0  \n   D   E   P   T   H       4  \n   M   A
0000040   X   V   A   L       2   5   5  \n   T   U   P   L   T   Y   P
0000060   E       R   G   B   _   A   L   P   H   A  \n   E   N   D   H
0000100   D   R  \n  \0  \0  \0  \0  \0  \0  \0  \0  \0  \0  \0  \0  \0
0000120  \0  \0  \0  \0  \0  \0  \0  \0  \0  \0  \0  \0  \0  \0  \0  \0
*
0000720  \0  \0  \0
0000723
```

**Comment by splace** [comment]
> Note that it's all zeroes,

ow yes, nul's, so my cut down code is no good!

**Comment by splace** [comment]
OK, i was confused with my system recognising pnm but not able to use the pam inside.

but my program, using netpbm, will now save pnm (pan inside) and read that back and save as other formats correctly. so was fixed previously.

**Comment by splace** [comment]
FYI  i found http://Convertio.co even though it claims support, was unable to handle these pam files, text or binary (returns unknown error), but http://onlineconvertfree.com works fine.

**Comment by spakin** [comment]
I just tried both sites, and both were able to handle the 10×10 black square from your sample code.  Is that what you tried, too?  If not, could you please upload a sample image that [https://convertio.co/](https://convertio.co/) is unable to convert, in case it turns out I'm misinterpreting the Netpbm image specification?

**Comment by splace** [comment]
here is the file that fails, it was converted from the gif below.

[flag.zip](https://github.com/spakin/netpbm/files/3397523/flag.zip)

![flag](https://user-images.githubusercontent.com/1234848/61302537-d8e4e000-a7dd-11e9-9d26-23de51068cec.gif)

**Comment by spakin** [comment]
I was able to reproduce the problem.  It looks like [https://convertio.co/](https://convertio.co/) is confused by the empty comment in the header:
```
P7
# 
WIDTH 256
HEIGHT 128
DEPTH 4
MAXVAL 255
TUPLTYPE RGB_ALPHA
ENDHDR
```
By removing the comment line, the Web site was able to convert the file.

— Scott

P.S.  `.pnm` isn't a valid file extension.  In this case, it should be `.pam`.  According to http://netpbm.sourceforge.net/doc/pam.html,

> "PNM" is not really a format. It is a shorthand for the PBM, PGM, and PPM formats collectively. It is also the name of a group of library functions that can each handle all three of those formats.

**Comment by splace** [comment]
>> "PNM" is not really a format. It is a shorthand for the PBM, PGM, and PPM formats collectively. It is also the name of a group of library functions that can each handle all three of those formats.

> P.S. .pnm isn't a valid file extension. In this case, it should be .pam. According to http://netpbm.sourceforge.net/doc/pam.html,

i don't think its saying that; 

i think it says; '.pnm' doesn't indicate an 'independent' format, as such, but that it indicates the file is from a group, all of which record inside the file what their underlying format is and do it in a specific way.

this (format indicated inside idea) is more a unix/internet type behaviour, where extensions are a liability, so this makes sense for portability.

this also seems to be backed-up by my system settings; my file manager happily assigns a mime type `PNM image (image/x-portable-anymap)` to an extension of '.pnm'.
