### ISSUE TITLE
Netpbm vs Netpbm11

### ISSUE THREAD

**Issue by jpajs** [spakin/netpbm#8]
Hello,

I am trying to use Netpbm in VMD. I used fink to install Netpbm11 but when I try to generate a movie, it says 'unable to locate pnmsmooth'. I thought 'pnmsmooth' was already in the package? I'm unsure what the difference is between Netpbm and Netpbm11. Does the latter not have a pbmsmooth?

**Comment by spakin** [comment]
I don't believe you're asking your question in the right forum.  https://github.com/spakin/netpbm provides a [Go](https://go.dev/) language interface to the Netpbm library, not a packaging of the Netpbm library and suite of applications.

According to https://pdb.finkproject.org/pdb/package.php/netpbm11, the maintainer of the Fink packaging of Netpbm is Hanspeter Niederstrasser <niederATusersDOTsourceforgeDOTnet>.  You might try asking your question of him.
