### ISSUE TITLE
integer divide by zero?

### ISSUE THREAD

**Issue by p7r0x7** [spakin/netpbm#9]
panic: runtime error: integer divide by zero

goroutine 5 [running]:
github.com/spakin/netpbm/npcolor.RGBM.RGBA(...)
	/Users/p7r0x7/go/pkg/mod/github.com/spakin/netpbm@v1.3.0/npcolor/npcolor.go:119
image/draw.drawRGBA(0x14000512000, {{0x14000512000?, 0x14000072e38?}, {0x10107cff0?, 0x1400050e000?}}, {0x10107cff0, 0x1400050e000}, {0x0?, 0x14000072e88?}, {0x0, ...}, ...)
	/opt/homebrew/Cellar/go/1.23.0/libexec/src/image/draw/draw.go:901 +0x3e8
image/draw.DrawMask({0x10107d1a0, 0x14000512000}, {{0x0, 0x0}, {0x10, 0x10}}, {0x10107cff0, 0x1400050e000}, {0x0, 0x0}, ...)
	/opt/homebrew/Cellar/go/1.23.0/libexec/src/image/draw/draw.go:210 +0x1528
image/draw.Draw(...)
	/opt/homebrew/Cellar/go/1.23.0/libexec/src/image/draw/draw.go:111
main.copyImage({0x10107cff0, 0x1400050e000})
	/Users/p7r0x7/Documents/rootq/main.go:109 +0xd8
main.main.func1()
	/Users/p7r0x7/Documents/rootq/main.go:52 +0xc4
created by main.main in goroutine 1
	/Users/p7r0x7/Documents/rootq/main.go:44 +0x5e8

**Comment by p7r0x7** [comment]
Found it:
```go
func copyImage(src image.Image) (image.Image, error) {
    if src == nil {
        return nil, fmt.Errorf("source image is nil")
    }

    bounds := src.Bounds()
    if bounds.Empty() {
        return nil, fmt.Errorf("source image bounds are empty")
    }

    dst := image.NewRGBA(bounds)
    draw.Draw(dst, dst.Bounds(), src, image.Point{}, draw.Src)
    return dst, nil
}
```

**Comment by spakin** [comment]
Thanks for providing code that triggers the error.  The divide-by-zero occurs only when converting an undefined (or erroneous) Netpbm color to RGBA.  I'll see if I can modify the conversion code to produce the corresponding RGBA color nonetheless.

**Comment by spakin** [comment]
I believe the latest commit should solve the problem.  Please re-open this issue if it does not.

Thanks again for the bug report.
